---

spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    database: PostgreSQL

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres
